/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostTaskRouteImport } from './routes/post-task'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as MessagesConversationIdRouteImport } from './routes/messages.$conversationId'
import { Route as ApiPublicTasksCreateRouteImport } from './routes/api.public.tasks-create'
import { Route as ApiPublicPiVerifyRouteImport } from './routes/api.public.pi-verify'
import { Route as ApiPublicNotificationsRouteImport } from './routes/api.public.notifications'
import { Route as ApiPublicBidsCreateRouteImport } from './routes/api.public.bids-create'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostTaskRoute = PostTaskRouteImport.update({
  id: '/post-task',
  path: '/post-task',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MessagesRoute,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => MessagesRoute,
} as any)
const ApiPublicTasksCreateRoute = ApiPublicTasksCreateRouteImport.update({
  id: '/api/public/tasks-create',
  path: '/api/public/tasks-create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiVerifyRoute = ApiPublicPiVerifyRouteImport.update({
  id: '/api/public/pi-verify',
  path: '/api/public/pi-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotificationsRoute = ApiPublicNotificationsRouteImport.update({
  id: '/api/public/notifications',
  path: '/api/public/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBidsCreateRoute = ApiPublicBidsCreateRouteImport.update({
  id: '/api/public/bids-create',
  path: '/api/public/bids-create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRouteWithChildren
  '/post-task': typeof PostTaskRoute
  '/profile': typeof ProfileRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/messages/': typeof MessagesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/public/bids-create': typeof ApiPublicBidsCreateRoute
  '/api/public/notifications': typeof ApiPublicNotificationsRoute
  '/api/public/pi-verify': typeof ApiPublicPiVerifyRoute
  '/api/public/tasks-create': typeof ApiPublicTasksCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/post-task': typeof PostTaskRoute
  '/profile': typeof ProfileRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/messages': typeof MessagesIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/api/public/bids-create': typeof ApiPublicBidsCreateRoute
  '/api/public/notifications': typeof ApiPublicNotificationsRoute
  '/api/public/pi-verify': typeof ApiPublicPiVerifyRoute
  '/api/public/tasks-create': typeof ApiPublicTasksCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRouteWithChildren
  '/post-task': typeof PostTaskRoute
  '/profile': typeof ProfileRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/messages/': typeof MessagesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/public/bids-create': typeof ApiPublicBidsCreateRoute
  '/api/public/notifications': typeof ApiPublicNotificationsRoute
  '/api/public/pi-verify': typeof ApiPublicPiVerifyRoute
  '/api/public/tasks-create': typeof ApiPublicTasksCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/messages'
    | '/post-task'
    | '/profile'
    | '/messages/$conversationId'
    | '/tasks/$taskId'
    | '/messages/'
    | '/tasks/'
    | '/api/public/bids-create'
    | '/api/public/notifications'
    | '/api/public/pi-verify'
    | '/api/public/tasks-create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/post-task'
    | '/profile'
    | '/messages/$conversationId'
    | '/tasks/$taskId'
    | '/messages'
    | '/tasks'
    | '/api/public/bids-create'
    | '/api/public/notifications'
    | '/api/public/pi-verify'
    | '/api/public/tasks-create'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/messages'
    | '/post-task'
    | '/profile'
    | '/messages/$conversationId'
    | '/tasks/$taskId'
    | '/messages/'
    | '/tasks/'
    | '/api/public/bids-create'
    | '/api/public/notifications'
    | '/api/public/pi-verify'
    | '/api/public/tasks-create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  PostTaskRoute: typeof PostTaskRoute
  ProfileRoute: typeof ProfileRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksIndexRoute: typeof TasksIndexRoute
  ApiPublicBidsCreateRoute: typeof ApiPublicBidsCreateRoute
  ApiPublicNotificationsRoute: typeof ApiPublicNotificationsRoute
  ApiPublicPiVerifyRoute: typeof ApiPublicPiVerifyRoute
  ApiPublicTasksCreateRoute: typeof ApiPublicTasksCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-task': {
      id: '/post-task'
      path: '/post-task'
      fullPath: '/post-task'
      preLoaderRoute: typeof PostTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/api/public/tasks-create': {
      id: '/api/public/tasks-create'
      path: '/api/public/tasks-create'
      fullPath: '/api/public/tasks-create'
      preLoaderRoute: typeof ApiPublicTasksCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-verify': {
      id: '/api/public/pi-verify'
      path: '/api/public/pi-verify'
      fullPath: '/api/public/pi-verify'
      preLoaderRoute: typeof ApiPublicPiVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notifications': {
      id: '/api/public/notifications'
      path: '/api/public/notifications'
      fullPath: '/api/public/notifications'
      preLoaderRoute: typeof ApiPublicNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bids-create': {
      id: '/api/public/bids-create'
      path: '/api/public/bids-create'
      fullPath: '/api/public/bids-create'
      preLoaderRoute: typeof ApiPublicBidsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MessagesRoute: MessagesRouteWithChildren,
  PostTaskRoute: PostTaskRoute,
  ProfileRoute: ProfileRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksIndexRoute: TasksIndexRoute,
  ApiPublicBidsCreateRoute: ApiPublicBidsCreateRoute,
  ApiPublicNotificationsRoute: ApiPublicNotificationsRoute,
  ApiPublicPiVerifyRoute: ApiPublicPiVerifyRoute,
  ApiPublicTasksCreateRoute: ApiPublicTasksCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
