/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationKeyDottxtRouteImport } from './routes/validation-key[.]txt'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostTaskRouteImport } from './routes/post-task'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as MessagesConversationIdRouteImport } from './routes/messages.$conversationId'
import { Route as ApiPublicValidationKeyRouteImport } from './routes/api.public.validation-key'
import { Route as ApiPublicTasksCreateRouteImport } from './routes/api.public.tasks-create'
import { Route as ApiPublicPiVerifyRouteImport } from './routes/api.public.pi-verify'
import { Route as ApiPublicNotificationsRouteImport } from './routes/api.public.notifications'
import { Route as ApiPublicMessagesSendRouteImport } from './routes/api.public.messages-send'
import { Route as ApiPublicMessagesListRouteImport } from './routes/api.public.messages-list'
import { Route as ApiPublicConversationsListRouteImport } from './routes/api.public.conversations-list'
import { Route as ApiPublicBidsListRouteImport } from './routes/api.public.bids-list'
import { Route as ApiPublicBidsCreateRouteImport } from './routes/api.public.bids-create'
import { Route as ApiPublicBidsAcceptRouteImport } from './routes/api.public.bids-accept'

const ValidationKeyDottxtRoute = ValidationKeyDottxtRouteImport.update({
  id: '/validation-key.txt',
  path: '/validation-key.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostTaskRoute = PostTaskRouteImport.update({
  id: '/post-task',
  path: '/post-task',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MessagesRoute,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => MessagesRoute,
} as any)
const ApiPublicValidationKeyRoute = ApiPublicValidationKeyRouteImport.update({
  id: '/api/public/validation-key',
  path: '/api/public/validation-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTasksCreateRoute = ApiPublicTasksCreateRouteImport.update({
  id: '/api/public/tasks-create',
  path: '/api/public/tasks-create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiVerifyRoute = ApiPublicPiVerifyRouteImport.update({
  id: '/api/public/pi-verify',
  path: '/api/public/pi-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotificationsRoute = ApiPublicNotificationsRouteImport.update({
  id: '/api/public/notifications',
  path: '/api/public/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMessagesSendRoute = ApiPublicMessagesSendRouteImport.update({
  id: '/api/public/messages-send',
  path: '/api/public/messages-send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMessagesListRoute = ApiPublicMessagesListRouteImport.update({
  id: '/api/public/messages-list',
  path: '/api/public/messages-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConversationsListRoute =
  ApiPublicConversationsListRouteImport.update({
    id: '/api/public/conversations-list',
    path: '/api/public/conversations-list',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBidsListRoute = ApiPublicBidsListRouteImport.update({
  id: '/api/public/bids-list',
  path: '/api/public/bids-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBidsCreateRoute = ApiPublicBidsCreateRouteImport.update({
  id: '/api/public/bids-create',
  path: '/api/public/bids-create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBidsAcceptRoute = ApiPublicBidsAcceptRouteImport.update({
  id: '/api/public/bids-accept',
  path: '/api/public/bids-accept',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRouteWithChildren
  '/post-task': typeof PostTaskRoute
  '/profile': typeof ProfileRoute
  '/validation-key.txt': typeof ValidationKeyDottxtRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/messages/': typeof MessagesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/public/bids-accept': typeof ApiPublicBidsAcceptRoute
  '/api/public/bids-create': typeof ApiPublicBidsCreateRoute
  '/api/public/bids-list': typeof ApiPublicBidsListRoute
  '/api/public/conversations-list': typeof ApiPublicConversationsListRoute
  '/api/public/messages-list': typeof ApiPublicMessagesListRoute
  '/api/public/messages-send': typeof ApiPublicMessagesSendRoute
  '/api/public/notifications': typeof ApiPublicNotificationsRoute
  '/api/public/pi-verify': typeof ApiPublicPiVerifyRoute
  '/api/public/tasks-create': typeof ApiPublicTasksCreateRoute
  '/api/public/validation-key': typeof ApiPublicValidationKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/post-task': typeof PostTaskRoute
  '/profile': typeof ProfileRoute
  '/validation-key.txt': typeof ValidationKeyDottxtRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/messages': typeof MessagesIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/api/public/bids-accept': typeof ApiPublicBidsAcceptRoute
  '/api/public/bids-create': typeof ApiPublicBidsCreateRoute
  '/api/public/bids-list': typeof ApiPublicBidsListRoute
  '/api/public/conversations-list': typeof ApiPublicConversationsListRoute
  '/api/public/messages-list': typeof ApiPublicMessagesListRoute
  '/api/public/messages-send': typeof ApiPublicMessagesSendRoute
  '/api/public/notifications': typeof ApiPublicNotificationsRoute
  '/api/public/pi-verify': typeof ApiPublicPiVerifyRoute
  '/api/public/tasks-create': typeof ApiPublicTasksCreateRoute
  '/api/public/validation-key': typeof ApiPublicValidationKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRouteWithChildren
  '/post-task': typeof PostTaskRoute
  '/profile': typeof ProfileRoute
  '/validation-key.txt': typeof ValidationKeyDottxtRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/messages/': typeof MessagesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/public/bids-accept': typeof ApiPublicBidsAcceptRoute
  '/api/public/bids-create': typeof ApiPublicBidsCreateRoute
  '/api/public/bids-list': typeof ApiPublicBidsListRoute
  '/api/public/conversations-list': typeof ApiPublicConversationsListRoute
  '/api/public/messages-list': typeof ApiPublicMessagesListRoute
  '/api/public/messages-send': typeof ApiPublicMessagesSendRoute
  '/api/public/notifications': typeof ApiPublicNotificationsRoute
  '/api/public/pi-verify': typeof ApiPublicPiVerifyRoute
  '/api/public/tasks-create': typeof ApiPublicTasksCreateRoute
  '/api/public/validation-key': typeof ApiPublicValidationKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/messages'
    | '/post-task'
    | '/profile'
    | '/validation-key.txt'
    | '/messages/$conversationId'
    | '/tasks/$taskId'
    | '/messages/'
    | '/tasks/'
    | '/api/public/bids-accept'
    | '/api/public/bids-create'
    | '/api/public/bids-list'
    | '/api/public/conversations-list'
    | '/api/public/messages-list'
    | '/api/public/messages-send'
    | '/api/public/notifications'
    | '/api/public/pi-verify'
    | '/api/public/tasks-create'
    | '/api/public/validation-key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/post-task'
    | '/profile'
    | '/validation-key.txt'
    | '/messages/$conversationId'
    | '/tasks/$taskId'
    | '/messages'
    | '/tasks'
    | '/api/public/bids-accept'
    | '/api/public/bids-create'
    | '/api/public/bids-list'
    | '/api/public/conversations-list'
    | '/api/public/messages-list'
    | '/api/public/messages-send'
    | '/api/public/notifications'
    | '/api/public/pi-verify'
    | '/api/public/tasks-create'
    | '/api/public/validation-key'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/messages'
    | '/post-task'
    | '/profile'
    | '/validation-key.txt'
    | '/messages/$conversationId'
    | '/tasks/$taskId'
    | '/messages/'
    | '/tasks/'
    | '/api/public/bids-accept'
    | '/api/public/bids-create'
    | '/api/public/bids-list'
    | '/api/public/conversations-list'
    | '/api/public/messages-list'
    | '/api/public/messages-send'
    | '/api/public/notifications'
    | '/api/public/pi-verify'
    | '/api/public/tasks-create'
    | '/api/public/validation-key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  PostTaskRoute: typeof PostTaskRoute
  ProfileRoute: typeof ProfileRoute
  ValidationKeyDottxtRoute: typeof ValidationKeyDottxtRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksIndexRoute: typeof TasksIndexRoute
  ApiPublicBidsAcceptRoute: typeof ApiPublicBidsAcceptRoute
  ApiPublicBidsCreateRoute: typeof ApiPublicBidsCreateRoute
  ApiPublicBidsListRoute: typeof ApiPublicBidsListRoute
  ApiPublicConversationsListRoute: typeof ApiPublicConversationsListRoute
  ApiPublicMessagesListRoute: typeof ApiPublicMessagesListRoute
  ApiPublicMessagesSendRoute: typeof ApiPublicMessagesSendRoute
  ApiPublicNotificationsRoute: typeof ApiPublicNotificationsRoute
  ApiPublicPiVerifyRoute: typeof ApiPublicPiVerifyRoute
  ApiPublicTasksCreateRoute: typeof ApiPublicTasksCreateRoute
  ApiPublicValidationKeyRoute: typeof ApiPublicValidationKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation-key.txt': {
      id: '/validation-key.txt'
      path: '/validation-key.txt'
      fullPath: '/validation-key.txt'
      preLoaderRoute: typeof ValidationKeyDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-task': {
      id: '/post-task'
      path: '/post-task'
      fullPath: '/post-task'
      preLoaderRoute: typeof PostTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/api/public/validation-key': {
      id: '/api/public/validation-key'
      path: '/api/public/validation-key'
      fullPath: '/api/public/validation-key'
      preLoaderRoute: typeof ApiPublicValidationKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tasks-create': {
      id: '/api/public/tasks-create'
      path: '/api/public/tasks-create'
      fullPath: '/api/public/tasks-create'
      preLoaderRoute: typeof ApiPublicTasksCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-verify': {
      id: '/api/public/pi-verify'
      path: '/api/public/pi-verify'
      fullPath: '/api/public/pi-verify'
      preLoaderRoute: typeof ApiPublicPiVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notifications': {
      id: '/api/public/notifications'
      path: '/api/public/notifications'
      fullPath: '/api/public/notifications'
      preLoaderRoute: typeof ApiPublicNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/messages-send': {
      id: '/api/public/messages-send'
      path: '/api/public/messages-send'
      fullPath: '/api/public/messages-send'
      preLoaderRoute: typeof ApiPublicMessagesSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/messages-list': {
      id: '/api/public/messages-list'
      path: '/api/public/messages-list'
      fullPath: '/api/public/messages-list'
      preLoaderRoute: typeof ApiPublicMessagesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/conversations-list': {
      id: '/api/public/conversations-list'
      path: '/api/public/conversations-list'
      fullPath: '/api/public/conversations-list'
      preLoaderRoute: typeof ApiPublicConversationsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bids-list': {
      id: '/api/public/bids-list'
      path: '/api/public/bids-list'
      fullPath: '/api/public/bids-list'
      preLoaderRoute: typeof ApiPublicBidsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bids-create': {
      id: '/api/public/bids-create'
      path: '/api/public/bids-create'
      fullPath: '/api/public/bids-create'
      preLoaderRoute: typeof ApiPublicBidsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bids-accept': {
      id: '/api/public/bids-accept'
      path: '/api/public/bids-accept'
      fullPath: '/api/public/bids-accept'
      preLoaderRoute: typeof ApiPublicBidsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MessagesRoute: MessagesRouteWithChildren,
  PostTaskRoute: PostTaskRoute,
  ProfileRoute: ProfileRoute,
  ValidationKeyDottxtRoute: ValidationKeyDottxtRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksIndexRoute: TasksIndexRoute,
  ApiPublicBidsAcceptRoute: ApiPublicBidsAcceptRoute,
  ApiPublicBidsCreateRoute: ApiPublicBidsCreateRoute,
  ApiPublicBidsListRoute: ApiPublicBidsListRoute,
  ApiPublicConversationsListRoute: ApiPublicConversationsListRoute,
  ApiPublicMessagesListRoute: ApiPublicMessagesListRoute,
  ApiPublicMessagesSendRoute: ApiPublicMessagesSendRoute,
  ApiPublicNotificationsRoute: ApiPublicNotificationsRoute,
  ApiPublicPiVerifyRoute: ApiPublicPiVerifyRoute,
  ApiPublicTasksCreateRoute: ApiPublicTasksCreateRoute,
  ApiPublicValidationKeyRoute: ApiPublicValidationKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
